language: ruby
rvm:
  - 2.1.4
  - 2.2.4
  - 2.3.0
  - rbx-3.14
env:
  global:
    - SHOW_SIDEKIQ=true
  matrix:
    - SIDEKIQ_VERSION="~>4.1.0"
    - SIDEKIQ_VERSION="~>4.0.2"
    - SIDEKIQ_VERSION="~>3.5.4"
    - SIDEKIQ_VERSION="~>3.4.2"
    - SIDEKIQ_VERSION="~>3.3.4"

before_install:
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle --version

script: bundle exec rake
services:
  - redis-server
