language: ruby
rvm:
  - 1.9.2
  - 1.9.3
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-19mode
env:
  global:
    - SHOW_SIDEKIQ=true
  matrix:
    - SIDEKIQ_VERSION="~> 2.5.7"
    - SIDEKIQ_VERSION="~> 2.6.6"
    - SIDEKIQ_VERSION="~> 2.7.5"
    - SIDEKIQ_VERSION="~> 2.8.0"
    - SIDEKIQ_VERSION="~> 2.9.0"
script: bundle exec rake